name: gestalt
description: A simple library to integrate plugins through a simple events system
authors: [ myth-MC, U8092 ]
version: '${project.version}'
api-version: 1.13
main: ovh.mythmc.gestalt.bukkit.BukkitGestaltPlugin