name: gestalt
description: A simple library to integrate plugins through a simple event-based feature system
authors: [ myth-MC, U8092 ]
version: '${project.parent.version}'
api-version: 1.13
folia-supported: true
main: ovh.mythmc.gestalt.bukkit.BukkitGestaltPlugin