#
# Gestalt is an annotation-based library that opens a plethora of
# possibilities to developers looking for a multi-platform
# and modern event handler solution.
#
# The library downloads on runtime (normally while the server
# is starting) to reduce needed effort from developers.
# Users can manually disable this behavior with a settings
# property.
#

# This defines the URL for the latest version's checksum:
checksum.1 = https://assets.mythmc.ovh/gestalt/MD5_CHECKSUM_

# This is where the library is downloaded from:
server.1 = https://assets.mythmc.ovh/gestalt/dev.jar
server.2 = https://github.com/myth-MC/gestalt/raw/refs/heads/main/gestalt-bukkit.jar